# Generated by Django 3.1.2 on 2020-11-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='specialty_code',
            field=models.CharField(default='', max_length=128),
        ),
    ]
