# Generated by Django 3.1.2 on 2020-11-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_specialty_specialty_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=512)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.specialty')),
            ],
        ),
    ]
