# Generated by Django 3.1.2 on 2020-11-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0002_schedule'),
        ('device', '0002_deviceschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.pacient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.service')),
            ],
        ),
    ]
