# Generated by Django 3.1.2 on 2020-11-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='results')),
                ('pacients_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.action')),
            ],
        ),
    ]
